-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Kitty transparrency
hl.window_rule({
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.9 override",
})

-- Handmade Hero debugging
hl.window_rule({
    name = "Handmade Hero transparency",
    match = {
        title = "^(Handmade Hero)$",
        focus = false,
    },
    -- TODO: manual review — unmapped window rule action: "border_size 0"
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
    opacity = 0.5,
    -- TODO: manual review — unmapped window rule action: "no_blur on"
})

-- Jetbrains product fixes
hl.window_rule({
    name = "Jetbrains fix",
    match = {
        class = "^(.*jetbrains.*)$",
        title = "^(win.*)$",
    },
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
    -- TODO: manual review — unmapped window rule action: "no_focus on"
})

hl.window_rule({
    name = "Jetbrains fix 2",
    match = {
        class = "^(.*jetbrains.*)$",
        title = "match:title ^\\\\s$",
    },
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
    -- TODO: manual review — unmapped window rule action: "no_focus on"
})

hl.window_rule({
    name = "Jetbrains fix 3",
    match = {
        class = "^jetbrains-.+$",
        float = 1,
    },
    tag = "+jb",
})

hl.window_rule({
    name = "Jetbrains fix 4",
    match = {
        tag = "jb",
    },
    -- TODO: manual review — unmapped window rule action: "stay_focused on"
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
})

hl.window_rule({
    name = "Path of Building",
    match = {
        class = "pobfrontend",
    },
    float = false,
})

hl.window_rule({
    name = "SAN notifications",
    match = {
        class = "^(steamachievementnotifierv.*)$",
        title = "^.*: Notification$",
    },
    -- TODO: manual review — unmapped window rule action: "border_size 0"
    float = true,
    move = "-670 420",
    workspace = "1 silent",
    -- TODO: manual review — unmapped window rule action: "no_blur on"
    -- TODO: manual review — unmapped window rule action: "no_focus on"
    -- TODO: manual review — unmapped window rule action: "no_shadow on"
    -- TODO: manual review — unmapped window rule action: "render_unfocused on"
})

hl.window_rule({
    name = "SAN Tracking notification",
    match = {
        class = "^(steamachievementnotifierv.*)$",
        title = "^.*: Now Tracking$",
    },
    -- TODO: manual review — unmapped window rule action: "border_size 0"
    float = true,
    move = "-860 460",
    workspace = "1 silent",
    -- TODO: manual review — unmapped window rule action: "no_blur on"
    -- TODO: manual review — unmapped window rule action: "no_focus on"
    -- TODO: manual review — unmapped window rule action: "no_shadow on"
    -- TODO: manual review — unmapped window rule action: "render_unfocused on"
    size = "610 110",
})

hl.window_rule({
    name = "SAN No Game Notification",
    match = {
        class = "^(steamachievementnotifierv.*)$",
        title = "^.*: No Game EXE$",
    },
    workspace = "special:hidden silent",
    -- TODO: manual review — unmapped window rule action: "no_blur on"
    -- TODO: manual review — unmapped window rule action: "no_focus on"
    -- TODO: manual review — unmapped window rule action: "no_shadow on"
    -- TODO: manual review — unmapped window rule action: "render_unfocused on"
    size = "0 0",
})

hl.window_rule({
    name = "Signal",
    match = {
        class = "^(signal)$",
    },
    workspace = "14",
})

-- new Steam notification fix
hl.window_rule({
    name = "Steam Toasts",
    match = {
        class = "^(steam)$",
        title = "^(.*notificationtoasts.*)$",
    },
    -- TODO: manual review — unmapped window rule action: "no_focus on"
    -- TODO: manual review — unmapped window rule action: "idle_inhibit none"
})

-- Unreal fix
--windowrule=unset on,match:class ^(UE4Editor)$,match:title ^\w*$
hl.window_rule({
    name = "Unreal 4",
    match = {
        class = "^(UE4Editor)$",
        title = "^\\w*$",
    },
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
    suppress_event = "activate",
})

--windowrule=unset,class:^(UnrealEditor)$,title:^\w*$
hl.window_rule({
    name = "Unreal 5 fix?",
    match = {
        class = "^(UnrealEditor)$",
        title = "^\\w*$",
    },
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
    suppress_event = "activate",
})

-- Force apps to open on a specific workspace
-- TODO: fix the firefox windows, found out you can start firefox instances with a unique class by setting --name, need to figure out what it does
hl.window_rule({
    match = {
        class = "^(firefox)$",
        title = "^(.*Handmade Hero.*)$",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        class = "^(firefox)$",
        title = "^(.*Giant Fox.*)$",
    },
    workspace = "5 silent",
})

hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(Steam)$",
    },
    workspace = "11 silent",
})

hl.window_rule({
    match = {
        class = "^(steam)$",
        title = "^(.*REsistance.*)$",
    },
    workspace = "11 silent",
})

hl.window_rule({
    match = {
        class = "^(vesktop)$",
        title = "^(Vesktop)$",
    },
    workspace = "12 silent",
})

hl.window_rule({
    match = {
        class = "^(firefox)$",
        title = "^(.*completionist.me.*)$",
    },
    workspace = "13 silent",
})

hl.window_rule({
    match = {
        class = "^(steamachievementnotifierv.*)$",
        title = "^(Steam Achievement Notifier \\(V.*\\))$",
    },
    workspace = "15 silent",
})

hl.window_rule({
    match = {
        class = "^(slack)$",
    },
    workspace = "16 silent",
})

hl.window_rule({
    match = {
        title = "^(LACT)$",
    },
    workspace = "19 silent",
})

hl.window_rule({
    match = {
        class = "^(.*Thunderbird)$",
    },
    workspace = "23 silent",
})

hl.window_rule({
    match = {
        title = "^(Jellyfin)$",
    },
    workspace = "24 silent",
})

-- Open steam games on "main" display even when not focussed
hl.window_rule({
    match = {
        class = "^(steam_app_[0-9]*)$",
    },
    monitor = "DP-1",
})

hl.window_rule({
    match = {
        class = "^(steam_proton)$",
    },
    monitor = "DP-1",
})

hl.window_rule({
    match = {
        class = "^(gamescope)$",
    },
    monitor = "DP-1",
})

hl.window_rule({
    match = {
        xdg_tag = "^(proton-game)$",
    },
    monitor = "DP-1",
})

-- TODO: remove after not playing monster hunter stories 1/2 anymore
hl.window_rule({
    match = {
        title = "^(MONSTER HUNTER STORIES)$",
    },
    -- TODO: manual review — unmapped window rule action: "fullscreen_state 2 2"
})

hl.window_rule({
    match = {
        class = "^(Godot)$",
    },
    -- TODO: manual review — unmapped window rule action: "tile on"
})

-- MMBNLC Vol.1 (Steam AppID 1798010) Wine virtual desktop
hl.window_rule({
    match = {
        class = "^(steam_app_1798010)$",
        title = "^(Wine Desktop)$",
        xwayland = 1,
    },
    suppress_event = "fullscreen maximize",
    float = true,
    size = "2560 1440",
    -- TODO: manual review — unmapped window rule action: "border_size 0"
    move = "440 0",
})

hl.window_rule({
    match = {
        class = "^(mmbn_lc.\\.exe)$",
        title = "^(MegaMan_BattleNetwork_LegacyCollection_Vol.)$",
    },
    suppress_event = "fullscreen maximize",
    float = true,
    size = "2560 1440",
    -- TODO: manual review — unmapped window rule action: "border_size 0"
    move = "440 0",
})

hl.window_rule({
    name = "mmbn1",
    match = {
        class = "^(steam_app_1798010)$",
    },
    -- TODO: manual review — unmapped window rule action: "border_size 0"
    float = true,
    size = "2560 1440",
    move = "440 0",
    --suppress_event = fullscreen maximize
})
